# Generated by Django 4.1.4 on 2022-12-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.CharField(max_length=200)),
                ('speciality', models.CharField(max_length=200, verbose_name='Especialidad')),
                ('languages', models.CharField(max_length=30, verbose_name='Idiomas')),
                ('gender', models.CharField(choices=[('FEM', 'Femenino'), ('MASC', 'Masculino')], max_length=50, verbose_name='Género')),
                ('locations', models.CharField(max_length=200, verbose_name='Locaciones')),
                ('phone', models.CharField(max_length=200, verbose_name='Teléfono')),
                ('image', models.FileField(upload_to='doctores', verbose_name='Imagen')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Dirección Web')),
                ('reference', models.TextField(verbose_name='Referencias')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctores',
                'ordering': ['-created'],
            },
        ),
    ]
